config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'

  get 'about' => 'pages#about'
  get 'contact' => 'pages#contact'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NyquilBabies</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>

    <!-- Navigation Bar -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container">
        <%= link_to "Nyquil Babies Premium Gold", root_path, class: "navbar-brand" %>
        <ul class="nav navbar-nav">
          <li class="nav-item"><%= link_to "Home", root_path, class: "nav-link" %></li>
          <li class="nav-item"><%= link_to "About", about_path, class: "nav-link" %></li>
          <li class="nav-item"><%= link_to "Contact", contact_path, class: "nav-link" %></li>
        </ul>
      </div>
    </nav>

    <%= yield %>

    <!-- Page Content -->
    

    <!-- Footer -->
    <footer class="small text-muted">
      <div class="container">
        <hr>
        <center>
          <p>2023 NyQuil Babies</p>
        </center>
      </div>
    </footer>

  </body>
</html>

app/views/pages/about.html.erb
<div class="jumbotron">
    <div class="container">
        <h1>About us</h1>
        <p>This will be a secure social media network for only our friends.</p>
    </div>
</div>

app/views/pages/contact.html.erb
<h1>Contact</h1>
<p>Placeholder contact page - may add Discord channel info here.</p>

app/views/pages/home.html.erb
<div class="jumbotron jumbotron-home">
    <div class="container">
        <h1>Welcome to NBPG</h1>
        <p>Have fun you filthy fucking degenerates.</p>
        <%= link_to "Learn more", "#", class: "btn btn-primary btn-lg" %>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="col-md-4">
            <h2>Heading</h2>
            <p>sugma sugma sugma sugma</p>
            <p><%= link_to "view details", "#", class: "btn btn-secondary" %></p>
    </div>
    <div class="col-md-4">
            <h2>Heading</h2>
            <p>sugma sugma sugma sugma</p>
            <p><%= link_to "view details", "#", class: "btn btn-secondary" %></p>
    </div>
    <div class="col-md-4">
            <h2>Heading</h2>
            <p>sugma sugma sugma sugma</p>
            <p><%= link_to "view details", "#", class: "btn btn-secondary" %></p>
        </div>
    </div>
</div>